name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0/1 0/1 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: intbjw/checkout@master
      - name: Update gist
        uses: intbjw/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b3f5ba2c84e8e524c10ca588825ff915
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
